【例3-1】创建ndarray数组。

In [1]:
import numpy as np

In [2]:

data1=[1,3,5,7] #列表
w1=np.array(data1)
print('w1:',w1)
data2=(2,4,6,8) #元组
w2=np.array(data2)
print('w2:',w2)
data3=[[1,2,3,4],[5,6,7,8]] #多维数组
w3=np.array(data3)
print('w3:',w3)


w1: [1 3 5 7]
w2: [2 4 6 8]
w3: [[1 2 3 4]
 [5 6 7 8]]


【例3-2】array函数中指定dtype。

In [3]:
w3=np.array([1,2,3,4],dtype='float64')
print(w3.dtype)


float64


【例3-3】利用arange创建数组。

In [4]:
warray=np.arange(10)
print(warray)


[0 1 2 3 4 5 6 7 8 9]


【例3-4】指定起始、终值的步长参数的arange。

In [5]:
warray=np.arange(0,1,0.2)
print(warray)


[0.  0.2 0.4 0.6 0.8]


【例3-5】利用linspace函数创建数组

In [6]:
warray = np.linspace(0,1,5)
print(warray)


[0.   0.25 0.5  0.75 1.  ]


【例3-6】利用logspace创建数组。

In [7]:
warray = np.linspace(0,1,5)
print(warray)


[0.   0.25 0.5  0.75 1.  ]


In [8]:
warray = np.logspace(0,1,5) 
#生成1-10间的具有5个元素的等比数列
print(warray)


[ 1.          1.77827941  3.16227766  5.62341325 10.        ]


【例3-7】zeros函数创建全零矩阵。

In [9]:
print("一维数组：",np.zeros(4))
print("而维数组：",np.zeros([3,3]))


一维数组： [0. 0. 0. 0.]
而维数组： [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


【例3-8】ones函数创建全1数组。

In [10]:
print(np.ones(5))
print(np.ones([2,3]))


[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


【例3-9】diag函数创建对角阵。

In [11]:
print(np.diag([1,2,3,4]))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [12]:
print('使用eye函数创建的数组为：\n',np.eye(3))

使用eye函数创建的数组为：
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


【例3-10】查看数组的属性。

In [13]:
warray = np.array([[1,2,3],[4,5,6]])
print('秩为：',warray.ndim)
print('形状为：',warray.shape)
print('元素个数为：',warray.size)


秩为： 2
形状为： (2, 3)
元素个数为： 6


【例3-11】设置数组的shape属性。

In [14]:
warray.shape = 3,2
print(warray)


[[1 2]
 [3 4]
 [5 6]]


【例3-12】数组的类型转换。

In [15]:
arr1 = np.arange(6)
print(arr1.dtype)
arr2 = arr1.astype(np.float64)
print(arr2.dtype)


int32
float64


【例3-13】生成随机整数。

In [16]:
arr = np.random.randint(100,200,size = (2,4))
print(arr)


[[110 174 157 102]
 [172 100 102 139]]


【例3-14】生成[0,1]之间的随机数组。

In [17]:
arr1 = np.random.rand(5)
print(arr1)
arr2 = np.random.rand(4,2)
print(arr2)


[0.96789138 0.33075943 0.26242381 0.6600394  0.46229659]
[[0.5990414  0.35926905]
 [0.44986037 0.25097046]
 [0.69300076 0.6991829 ]
 [0.97807338 0.23423321]]


【例3-15】改变数组维度。

In [18]:
arr1 = np.arange(8)
print(arr1)
arr1.reshape(4,2)
print(arr1)


[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


【例3-16】reshape的一个维度设置为-1。

In [19]:
arr1 = np.arange(12)
print('arr1:',arr1)
arr2 = arr1.reshape(2,-1)
print('arr2:',arr2)


arr1: [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr2: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


【例3-17】数据散开。

In [20]:
arr1 = np.arange(12).reshape(3,4)
print('arr1:',arr1)
arr2 = arr1.ravel()
print('arr2:',arr2)


arr1: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr2: [ 0  1  2  3  4  5  6  7  8  9 10 11]


【例3-18】两个数组的横向组合。

In [21]:
arr1 = np.arange(6).reshape(3,2)
arr2 = arr1*2
arr3 = np.hstack((arr1,arr2))
print(arr3)


[[ 0  1  0  2]
 [ 2  3  4  6]
 [ 4  5  8 10]]


【例3-19】数组纵向合并。

In [22]:
arr1 = np.arange(6).reshape(3,2)
arr2 = arr1*2
arr3 = np.vstack((arr1,arr2))
print(arr3)


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 0  2]
 [ 4  6]
 [ 8 10]]


【例3-20】concatenate函数合并数组。

In [23]:
arr1 = np.arange(6).reshape(3,2)
arr2 = arr1*2
print('横向组合为：\n',np.concatenate((arr1,arr2),axis = 1))
print('纵向组合为：\n',np.concatenate((arr1,arr2),axis = 0))


横向组合为：
 [[ 0  1  0  2]
 [ 2  3  4  6]
 [ 4  5  8 10]]
纵向组合为：
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 0  2]
 [ 4  6]
 [ 8 10]]


【例3-21】数组的分割。

In [24]:
arr = np.arange(16).reshape(4,4)
print('横向分割为:\n',np.hsplit(arr,2))
print('纵向组合为:\n',np.vsplit(arr,2))


横向分割为:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
纵向组合为:
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


【例3-22】数组利用transpose转置。

In [25]:
arr = np.arange(6).reshape(3,2)
print('矩阵：',arr)
print('转置矩阵：',arr.transpose((1,0)))


矩阵： [[0 1]
 [2 3]
 [4 5]]
转置矩阵： [[0 2 4]
 [1 3 5]]


【例3-23】数组的T属性转置。

In [26]:
print(arr.T)

[[0 2 4]
 [1 3 5]]


【例3-24】数组的轴对换。

In [27]:
arr = np.arange(6).reshape(3,2)
print(arr)
print(arr.swapaxes(0,1))


[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]


【例3-25】一维数组的索引。

In [28]:
arr = np.arange(10)
print(arr)
print(arr[2])
print(arr[-1])
print(arr[1:4])


[0 1 2 3 4 5 6 7 8 9]
2
9
[1 2 3]


【例3-26】数组元素的复制。

In [29]:
arr1 = arr[-4:-1].copy()
print(arr)
print(arr1)


[0 1 2 3 4 5 6 7 8 9]
[6 7 8]


【例3-27】多维数组的索引。

In [1]:
import numpy as np
arr = np.arange(12).reshape(3,4)
print(arr)
print(arr[0,1:3])  #索引第0行中第1列到第2列的元素
print(arr[:,2])   #索引第2列元素
print(arr[:1,:1])  #第0行第0列元素


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2]
[ 2  6 10]
[[0]]


【例3-28】访问多维数组。

In [9]:
import numpy as np
arr = np.arange(12).reshape(3,4)
#从两个序列的对应位置取出两个整数来组成下标：arr[0,1],arr[1,3]
print(arr)
print('索引结果1：',arr[(0,1),(1,3)])
#索引第1、2行中第0、2、3列的元素
print('索引结果2：',arr[1:2,(0,2,3)])
mask = np.array([1,0,1],dtype = np.bool)
print(mask)
#mask是一个布尔数组，它索引第0,2行中第1列元素
print('索引结果3：',arr[mask,1])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
索引结果1： [1 7]
索引结果2： [[4 6 7]]
[ True False  True]
索引结果3： [1 9]


C:\Users\DIYcat\AppData\Local\Temp/ipykernel_7144/18514711.py:8: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask = np.array([1,0,1],dtype = np.bool)


【例3-29】数组元素的追加。

In [3]:
import numpy as np
a = [1,2,3]
b = np.array([1,2,3])
b_a = np.append(b,a)
print('b_a数组：',b_a)
wy = np.array([1,2,3])
c = wy*2
print('c数组：',c)


b_a数组： [1 2 3 1 2 3]
c数组： [2 4 6]


【例3-30】数组的四则运算。

In [4]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
print('数组相加结果：',x+y)
print('数组相减结果：',x-y)
print('数组相乘结果：',x*y)
print('数组幂运算结果：',x**y)


数组相加结果： [5 7 9]
数组相减结果： [-3 -3 -3]
数组相乘结果： [ 4 10 18]
数组幂运算结果： [  1  32 729]


【例3-31】数组的比较运算。

In [10]:
import numpy as np
x = np.array([1,3,6])
y = np.array([2,3,4])
print('比较结果(<)：',x<y)
print('比较结果(>)：',x>y)
print('比较结果(==)：',x==y)
print('比较结果(>=)：',x>=y)
print('比较结果(!=)：',x!=y)


比较结果(<)： [ True False False]
比较结果(>)： [False False  True]
比较结果(==)： [False  True False]
比较结果(>=)： [False  True  True]
比较结果(!=)： [ True False  True]


【例3-32】ufunc函数的广播。

In [11]:
import numpy as np
arr1 = np.array([[0,0,0],[1,1,1],[2,2,2]])
arr2 = np.array([1,2,3])
print('arr1:\n',arr1)
print('arr2:\n',arr2)
print('arr1+arr2:\n',arr1+arr2)

arr1:
 [[0 0 0]
 [1 1 1]
 [2 2 2]]
arr2:
 [1 2 3]
arr1+arr2:
 [[1 2 3]
 [2 3 4]
 [3 4 5]]


In [36]:
a = np.arange(1, 13).reshape(4, 3) 
b = np.arange(1,5).reshape(4,1)
print(a)
print(b)
print(a+b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1]
 [2]
 [3]
 [4]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


【例3-33】数组的条件逻辑运算。

In [13]:
import numpy as np
arr1 = np.array([1,3,5,7])
arr2 = np.array([2,4,6,8])
cond = np.array([True,False,True,False])
result = [(x if c else y)for x,y,c in zip(arr1,arr2,cond)]
result


[1, 4, 5, 8]

【例3-34】where的基本用法。

In [38]:
np.where([[True,False], [True,True]],[[1,2], [3,4]],[[9,8], [7,6]])

array([[1, 8],
       [3, 4]])

【例3-35】where中只有condition参数。

In [39]:
w = np.array([2,5,6,3,10])
np.where(w>4)


(array([1, 2, 4], dtype=int64),)

【例3-36】数组的读写。

In [40]:
a = np.arange(1,13).reshape(3,4)
print(a)
np.save('arr.npy', a)      # np.save("arr", a)
c = np.load( 'arr.npy' )
print(c)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


【例3-37】多个数组保存。

In [41]:
a = np.array([[1,2,3],[4,5,6]])
b = np.arange(0, 1.0, 0.1)
c = np.sin(b)   #长度为10
print(c)
np.savez('result.npz', a, b, sin_array = c)
r = np.load('result.npz')
r['arr_0']   #数组a


[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691]


array([[1, 2, 3],
       [4, 5, 6]])

【例3-38】读写文本文件。

In [42]:
a = np.arange(0,12,0.5).reshape(4,-1)
np.savetxt("data//a1-out.txt", a)  
#缺省按照'%.18e'格式保存数值
np.loadtxt("data//a1-out.txt")
np.savetxt("data//a2-out.txt", a, fmt = "%d", delimiter = ",") 
#改为保存为整数，以逗号分隔
np.loadtxt("data//a2-out.txt",delimiter = ",") 
# 读入的时候也需要指定逗号分隔


array([[ 0.,  0.,  1.,  1.,  2.,  2.],
       [ 3.,  3.,  4.,  4.,  5.,  5.],
       [ 6.,  6.,  7.,  7.,  8.,  8.],
       [ 9.,  9., 10., 10., 11., 11.]])

【例3-39】使用sort函数进行排序。

In [43]:
arr = np.array([7,9,5,2,9,4,3,1,4,3])
print('原数组：',arr)
arr.sort()
print('排序后：',arr)


原数组： [7 9 5 2 9 4 3 1 4 3]
排序后： [1 2 3 3 4 4 5 7 9 9]


【例3-40】带轴向参数的sort排序。

In [44]:
arr = np.array([[4,2,9,5],[6,4,8,3],[1,6,2,4]])
print('原数组：\n',arr)
arr.sort(axis = 1)   #沿横向排序
print('横向排序后：\n',arr)


原数组：
 [[4 2 9 5]
 [6 4 8 3]
 [1 6 2 4]]
横向排序后：
 [[2 4 5 9]
 [3 4 6 8]
 [1 2 4 6]]


【例3-41】使用argsort函数进行排序。

In [45]:
arr = np.array([7,9,5,2,9,4,3,1,4,3])
print('原数组：',arr)
print('排序后：',arr.argsort())
#返回值为数组排序后的下标排列
print('显示较大的5个数：',arr[arr.argsort()][-5:])


原数组： [7 9 5 2 9 4 3 1 4 3]
排序后： [7 3 6 9 5 8 2 0 1 4]
显示较大的5个数： [4 5 7 9 9]


【例3-42】使用lexsort排序。

In [46]:
a = [1,5,7,2,3,-2,4]
b = [9,5,2,0,6,8,7]
ind=np.lexsort((b,a))
print('ind:',ind)
tmp=[(a[i],b[i])for i in ind]
print('tmp:',tmp)


ind: [5 0 3 4 6 1 2]
tmp: [(-2, 8), (1, 9), (2, 0), (3, 6), (4, 7), (5, 5), (7, 2)]


【例3-43】数组内数据去重。

In [47]:
names = np.array(['红色','蓝色','蓝色','白色','红色','红色'])
print('原数组：',names)
print('去重后的数组:',np.unique(names)) 
print('数据出现次数:',np.unique(names,return_counts=True))



原数组： ['红色' '蓝色' '蓝色' '白色' '红色' '红色']
去重后的数组: ['白色' '红色' '蓝色']
数据出现次数: (array(['白色', '红色', '蓝色'], dtype='<U2'), array([1, 3, 2], dtype=int64))


【例3-44】使用tile函数实现数据重复。

In [48]:
arr = np.arange(5)
print('原数组：',arr)
wy = np.tile(arr,3)
print('重复数据处理：\n',wy)


原数组： [0 1 2 3 4]
重复数据处理：
 [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


【例3-45】使用repeat函数实现数据重复。

In [49]:
arr = np.arange(5)
print('原数组：',arr)
wy = np.tile(arr,3)
print('重复数据处理：\n',wy)
arr2 = np.array([[1,2,3],[4,5,6]])
print('重复数据处理：\n',arr2.repeat(2,axis=0)) 


原数组： [0 1 2 3 4]
重复数据处理：
 [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
重复数据处理：
 [[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


【例3-46】NumPy中常用函数的使用。

In [50]:
arr = np.arange(20).reshape(4,5)
print('创建的数组：\n',arr)
print('数组的和：',np.sum(arr))
print('数组纵轴的和：',np.sum(arr,axis = 0))
print('数组横轴的和：',np.sum(arr,axis = 1))
print('数组的均值：',np.mean(arr))
print('数组横轴的均值：',np.mean(arr,axis = 1))
print('数组的标准差：',np.std(arr))
print('数组横轴的标准差：',np.std(arr,axis = 1))


创建的数组：
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
数组的和： 190
数组纵轴的和： [30 34 38 42 46]
数组横轴的和： [10 35 60 85]
数组的均值： 9.5
数组横轴的均值： [ 2.  7. 12. 17.]
数组的标准差： 5.766281297335398
数组横轴的标准差： [1.41421356 1.41421356 1.41421356 1.41421356]
